CLASS
 NAME "0 5"
 GROUP "HUMIDITYREL"
 EXPRESSION ([pixel] >= 0.00 AND [pixel] < 5.00)
 STYLE
  COLOR 0 0 121
 END
END

CLASS
 NAME "05 10"
 GROUP "HUMIDITYREL"
 EXPRESSION ([pixel] >= 5.00 AND [pixel] < 10.00)
 STYLE
  COLOR 0 0 171                                                                                                                                                                                                                                     
 END                                                                                                                                                                                                                           
END                                                                                                                                                                                                                            
                                                                                                                                                                                                                                             
CLASS                                                                                                                                                                                                                                       
 NAME "10 15"   
 GROUP "HUMIDITYREL"
 EXPRESSION ([pixel] >= 10.00 AND [pixel] < 15.00)                                                                                                                                                                                          
 STYLE                                                                                                                                                                                                                                      
  COLOR 0 0 216                                                                                                                                                                                                                                    
 END                                                                                                                                                                                                                           
END                                                                                                                                                                                                                            
                                                                                                                                                                                                                                             
CLASS                                                                                                                                                                                                                                       
 NAME "15 20" 
 GROUP "HUMIDITYREL"
 EXPRESSION ([pixel] >= 15.00 AND [pixel] < 20.00)                                                                                                                                                                                          
 STYLE                                                                                                                                                                                                                                      
  COLOR 0 9 254                                                                                                                                                                                                                                    
 END                                                                                                                                                                                                                           
END                                                                                                                                                                                                                            
                                                                                                                                                                                                                                             
CLASS                                                                                                                                                                                                                                       
 NAME "20 25"  
 GROUP "HUMIDITYREL"
 EXPRESSION ([pixel] >= 20.00 AND [pixel] < 25.00)                                                                                                                                                                                          
 STYLE                                                                                                                                                                                                                                      
  COLOR 0 76 254                                                                                                                                                                                                                                    
 END                                                                                                                                                                                                                           
END

CLASS
 NAME "25 30"
 GROUP "HUMIDITYREL"
 EXPRESSION ([pixel] >= 25.00 AND [pixel] < 30.00)
 STYLE
  COLOR 0 143 254
 END
END

CLASS
 NAME "30 35"
 GROUP "HUMIDITYREL"
 EXPRESSION ([pixel] >= 30.00 AND [pixel] < 35.00)
 STYLE
  COLOR 0 209 254
 END
END

CLASS
 NAME "35 40"
 GROUP "HUMIDITYREL"
 EXPRESSION ([pixel] >= 35.00 AND [pixel] < 40.00)
 STYLE
  COLOR 18 253 236
 END
END

CLASS
 NAME "40 45"
 GROUP "HUMIDITYREL"
 EXPRESSION ([pixel] >= 40.00 AND [pixel] < 45.00)
 STYLE
  COLOR 72 253 182
 END
END

CLASS
 NAME "45 50"
 GROUP "HUMIDITYREL"
 EXPRESSION ([pixel] >= 45.00 AND [pixel] < 50.00)
 STYLE
  COLOR 126 253 128
 END
END

CLASS
 NAME "50 55"
 GROUP "HUMIDITYREL"
 EXPRESSION ([pixel] >= 50.00 AND [pixel] < 55.00)
 STYLE
  COLOR 179 254 75
 END
END

CLASS
 NAME "55 60"
 GROUP "HUMIDITYREL"
 EXPRESSION ([pixel] >= 55.00 AND [pixel] < 60.00)
 STYLE
  COLOR 233 254 21
 END
END

CLASS
 NAME "60 65"
 GROUP "HUMIDITYREL"
 EXPRESSION ([pixel] >= 60.00 AND [pixel] < 65.00)
 STYLE
  COLOR 254 222 0
 END
END

CLASS
 NAME "65 70"
 GROUP "HUMIDITYREL"
 EXPRESSION ([pixel] >= 65.00 AND [pixel] < 70.00)
 STYLE
  COLOR 254 169 0
 END
END

CLASS
 NAME "70 75"
 GROUP "HUMIDITYREL"
 EXPRESSION ([pixel] >= 70.00 AND [pixel] < 75.00)
 STYLE
  COLOR 254 115 0
 END
END

CLASS
 NAME "75 80"
 GROUP "HUMIDITYREL"
 EXPRESSION ([pixel] >= 75.00 AND [pixel] < 80.00)
 STYLE
  COLOR 254 61 0
 END
END

CLASS
 NAME "80 85"
 GROUP "HUMIDITYREL"
 EXPRESSION ([pixel] >= 80.00 AND [pixel] < 85.00)
 STYLE
  COLOR 254 8 0
 END
END

CLASS
 NAME "85 90"
 GROUP "HUMIDITYREL"
 EXPRESSION ([pixel] >= 85.00 AND [pixel] < 90.00)
 STYLE
  COLOR 216 0 0
 END
END

CLASS
 NAME "90 95"
 GROUP "HUMIDITYREL"
 EXPRESSION ([pixel] >= 90.00 AND [pixel] < 95.00)
 STYLE
  COLOR 171 0 0
 END
END

CLASS
 NAME "95 100"
 GROUP "HUMIDITYREL"
 EXPRESSION ([pixel] >= 95.00 AND [pixel] <= 100.00)
 STYLE
  COLOR 127 0 0
 END
END
