CLASS
 NAME "0.00 0.05 m/s"
 GROUP "SEA_CURARROW_100MTO2000M"
 EXPRESSION ([uv_length] >= 0.00 AND [uv_length] < 0.05)
 STYLE
  SYMBOL "arrow_wind"
  COLOR 153 232 253
   ANGLE [uv_angle]
  SIZE 10
 END
  TEXT " "
   LABEL
  SIZE 4
   ANGLE 45
 END
END
CLASS
 NAME "0.05 0.10 m/s"
 GROUP "SEA_CURARROW_100MTO2000M"
 EXPRESSION ([uv_length] >= 0.05 AND [uv_length] < 0.10)
 STYLE
  SYMBOL "arrow_wind"
  COLOR 153 148 255
   ANGLE [uv_angle]
  SIZE 10
 END
  TEXT " "
   LABEL
  SIZE 4
   ANGLE 45
 END
END
CLASS
 NAME "0.10 0.15 m/s"
 GROUP "SEA_CURARROW_100MTO2000M"
 EXPRESSION ([uv_length] >= 0.10 AND [uv_length] < 0.15)
 STYLE
  SYMBOL "arrow_wind"
  COLOR 154 64 249
   ANGLE [uv_angle]
  SIZE 10
 END
  TEXT " "
   LABEL
  SIZE 4
   ANGLE 45
 END
END
CLASS
 NAME "0.15 0.20 m/s"
 GROUP "SEA_CURARROW_100MTO2000M"
 EXPRESSION ([uv_length] >= 0.15 AND [uv_length] < 0.20)
 STYLE
  SYMBOL "arrow_wind"
  COLOR 204 135 254
   ANGLE [uv_angle]
  SIZE 10
 END
  TEXT " "
   LABEL
  SIZE 4
   ANGLE 45
 END
END
CLASS
 NAME "0.20 0.25 m/s"
 GROUP "SEA_CURARROW_100MTO2000M"
 EXPRESSION ([uv_length] >= 0.20 AND [uv_length] < 0.25)
 STYLE
  SYMBOL "arrow_wind"
  COLOR 128 255 100
   ANGLE [uv_angle]
  SIZE 10
 END
  TEXT " "
   LABEL
  SIZE 4
   ANGLE 45
 END
END
CLASS
 NAME "0.25 0.30 m/s"
 GROUP "SEA_CURARROW_100MTO2000M"
 EXPRESSION ([uv_length] >= 0.25 AND [uv_length] < 0.30)
 STYLE
  SYMBOL "arrow_wind"
  COLOR 209 254 45
   ANGLE [uv_angle]
  SIZE 10
 END
  TEXT " "
   LABEL
  SIZE 4
   ANGLE 45
 END
END
CLASS
 NAME "0.30 0.35 m/s"
 GROUP "SEA_CURARROW_100MTO2000M"
 EXPRESSION ([uv_length] >= 0.30 AND [uv_length] < 0.35)
 STYLE
  SYMBOL "arrow_wind"
  COLOR 255 217 0
   ANGLE [uv_angle]
  SIZE 10
 END
  TEXT " "
   LABEL
  SIZE 4
   ANGLE 45
 END
END
CLASS
 NAME "0.35 0.40 m/s"
 GROUP "SEA_CURARROW_100MTO2000M"
 EXPRESSION ([uv_length] >= 0.35 AND [uv_length] < 0.40)
 STYLE
  SYMBOL "arrow_wind"
  COLOR 255 128 0
   ANGLE [uv_angle]
  SIZE 10
 END
  TEXT " "
   LABEL
  SIZE 4
   ANGLE 45
 END
END
CLASS
 NAME "0.40 0.45 m/s"
 GROUP "SEA_CURARROW_100MTO2000M"
 EXPRESSION ([uv_length] >= 0.40 AND [uv_length] < 0.45)
 STYLE
  SYMBOL "arrow_wind"
  COLOR 255 51 0
   ANGLE [uv_angle]
  SIZE 10
 END
  TEXT " "
   LABEL
  SIZE 4
   ANGLE 45
 END
END
CLASS
 NAME "0.45 0.50 m/s"
 GROUP "SEA_CURARROW_100MTO2000M"
 EXPRESSION ([uv_length] >= 0.45 AND [uv_length] < 0.50)
 STYLE
  SYMBOL "arrow_wind"
  COLOR 222 0 0
   ANGLE [uv_angle]
  SIZE 10
 END
  TEXT " "
   LABEL
  SIZE 4
   ANGLE 45
 END
END
CLASS
 NAME "0.50 m/s +"
 GROUP "SEA_CURARROW_100MTO2000M"
 EXPRESSION ([uv_length] >= 0.50 AND [uv_length] < 5.00)
 STYLE
  SYMBOL "arrow_wind"
  COLOR 128 0 0
   ANGLE [uv_angle]
  SIZE 10
 END
  TEXT " "
   LABEL
  SIZE 4
   ANGLE 45
 END
END
