CLASS
 NAME "0.0 - 0.1"
 GROUP "SEA_ICEDRIFT-CIS"
 EXPRESSION (0.0 <= [uv_length] AND [uv_length] < 0.1)
 STYLE
  SYMBOL "arrow"
  COLOR 204 135 254
  ANGLE [uv_angle]
  SIZE 10
 END
END
CLASS
 NAME "0.1 - 0.2"
 GROUP "SEA_ICEDRIFT-CIS"
 EXPRESSION (0.1 <= [uv_length] AND [uv_length] < 0.2)
 STYLE
  SYMBOL "arrow"
  COLOR 154 064 249
  ANGLE [uv_angle]
  SIZE 10
 END
END
CLASS
 NAME "0.2 - 0.3"
 GROUP "SEA_ICEDRIFT-CIS"
 EXPRESSION (0.2 <= [uv_length] AND [uv_length] < 0.3)
 STYLE
  SYMBOL "arrow"
  COLOR 153 148 255
  ANGLE [uv_angle]
  SIZE 10
 END
END
CLASS
 NAME "0.3 - 0.4"
 GROUP "SEA_ICEDRIFT-CIS"
 EXPRESSION (0.3 <= [uv_length] AND [uv_length] < 0.4)
 STYLE
  SYMBOL "arrow"
  COLOR 153 232 253
  ANGLE [uv_angle]
  SIZE 10
 END
END
CLASS
 NAME "0.4 - 0.5"
 GROUP "SEA_ICEDRIFT-CIS"
 EXPRESSION (0.4 <= [uv_length] AND [uv_length] < 0.5)
 STYLE
  SYMBOL "arrow"
  COLOR 032 154 230
  ANGLE [uv_angle]
  SIZE 10
 END
END
CLASS
 NAME "0.5 - 1.0"
 GROUP "SEA_ICEDRIFT-CIS"
 EXPRESSION (0.5 <= [uv_length] AND [uv_length] < 1.0)
 STYLE
  SYMBOL "arrow"
  COLOR 000 102 255
  ANGLE [uv_angle]
  SIZE 10
 END
END
CLASS
 NAME "1.0 - 10.0"
 GROUP "SEA_ICEDRIFT-CIS"
 EXPRESSION (1.0 <= [uv_length] AND [uv_length] <= 10.0)
 STYLE
  SYMBOL "arrow"
  COLOR 000 000 128
  ANGLE [uv_angle]
  SIZE 10
 END
END
