CLASS
 NAME "0.01 - 0.11"
 GROUP "SEA_ICESSCUR-CIS"
 EXPRESSION (0.01 <= [uv_length] AND [uv_length] < 0.11)
 STYLE
  SYMBOL "arrow"
  COLOR 026 026 255
  ANGLE [uv_angle]
  SIZE 10
 END
END
CLASS
 NAME "0.11 - 0.21"
 GROUP "SEA_ICESSCUR-CIS"
 EXPRESSION (0.11 <= [uv_length] AND [uv_length] < 0.21)
 STYLE
  SYMBOL "arrow"
  COLOR 077 121 255
  ANGLE [uv_angle]
  SIZE 10
 END
END
CLASS
 NAME "0.21 - 0.32"
 GROUP "SEA_ICESSCUR-CIS"
 EXPRESSION (0.21 <= [uv_length] AND [uv_length] < 0.32)
 STYLE
  SYMBOL "arrow"
  COLOR 000 255 255
  ANGLE [uv_angle]
  SIZE 10
 END
END
CLASS
 NAME "0.32 - 0.43"
 GROUP "SEA_ICESSCUR-CIS"
 EXPRESSION (0.32 <= [uv_length] AND [uv_length] < 0.43)
 STYLE
  SYMBOL "arrow"
  COLOR 153 255 253
  ANGLE [uv_angle]
  SIZE 10
 END
END
CLASS
 NAME "0.43 - 0.54"
 GROUP "SEA_ICESSCUR-CIS"
 EXPRESSION (0.43 <= [uv_length] AND [uv_length] < 0.54)
 STYLE
  SYMBOL "arrow"
  COLOR 255 237 000
  ANGLE [uv_angle]
  SIZE 10
 END
END
CLASS
 NAME "0.54 - 0.65"
 GROUP "SEA_ICESSCUR-CIS"
 EXPRESSION (0.54 <= [uv_length] AND [uv_length] < 0.65)
 STYLE
  SYMBOL "arrow"
  COLOR 255 124 000
  ANGLE [uv_angle]
  SIZE 10
 END
END
CLASS
 NAME "0.65 - 1.00"
 GROUP "SEA_ICESSCUR-CIS"
 EXPRESSION (0.65 <= [uv_length] AND [uv_length] <= 1.00)
 STYLE
  SYMBOL "arrow"
  COLOR 255 000 000
  ANGLE [uv_angle]
  SIZE 10
 END
END
