CLASS
 NAME "0 10"
 GROUP "SEA_CURARROW"
 EXPRESSION ([uv_length] >= 0.02 AND [uv_length] < 0.5)
 STYLE
  SYMBOL "arrow_wind"
  COLOR 153 232 253
   ANGLE [uv_angle]
  SIZE 10
 END
  TEXT " "
   LABEL
  SIZE 4
   ANGLE 45
 END
END
CLASS
 NAME "10 20"
 GROUP "SEA_CURARROW"
 EXPRESSION ([uv_length] >= 0.5 AND [uv_length] < 1)
 STYLE
  SYMBOL "arrow_wind"
  COLOR 153 148 255
   ANGLE [uv_angle]
  SIZE 10
 END
  TEXT " "
   LABEL
  SIZE 4
   ANGLE 45
 END
END
CLASS
 NAME "20 30"
 GROUP "SEA_CURARROW"
 EXPRESSION ([uv_length] >= 1 AND [uv_length] < 1.5)
 STYLE
  SYMBOL "arrow_wind"
  COLOR 154 64 249
   ANGLE [uv_angle]
  SIZE 10
 END
  TEXT " "
   LABEL
  SIZE 4
   ANGLE 45
 END
END
CLASS
 NAME "30 40"
 GROUP "SEA_CURARROW"
 EXPRESSION ([uv_length] >= 1.5 AND [uv_length] < 2)
 STYLE
  SYMBOL "arrow_wind"
  COLOR 204 135 254
   ANGLE [uv_angle]
  SIZE 10
 END
  TEXT " "
   LABEL
  SIZE 4
   ANGLE 45
 END
END
CLASS
 NAME "40 50"
 GROUP "SEA_CURARROW"
 EXPRESSION ([uv_length] >= 2 AND [uv_length] < 2.5)
 STYLE
  SYMBOL "arrow_wind"
  COLOR 128 255 100
   ANGLE [uv_angle]
  SIZE 10
 END
  TEXT " "
   LABEL
  SIZE 4
   ANGLE 45
 END
END
CLASS
 NAME "50 60"
 GROUP "SEA_CURARROW"
 EXPRESSION ([uv_length] >= 2.5 AND [uv_length] < 3)
 STYLE
  SYMBOL "arrow_wind"
  COLOR 209 254 45
   ANGLE [uv_angle]
  SIZE 10
 END
  TEXT " "
   LABEL
  SIZE 4
   ANGLE 45
 END
END
CLASS
 NAME "60 70"
 GROUP "SEA_CURARROW"
 EXPRESSION ([uv_length] >= 3 AND [uv_length] < 4)
 STYLE
  SYMBOL "arrow_wind"
  COLOR 255 217 0
   ANGLE [uv_angle]
  SIZE 10
 END
  TEXT " "
   LABEL
  SIZE 4
   ANGLE 45
 END
END
CLASS
 NAME "70 80"
 GROUP "SEA_CURARROW"
 EXPRESSION ([uv_length] >= 4 AND [uv_length] < 5)
 STYLE
  SYMBOL "arrow_wind"
  COLOR 255 128 0
   ANGLE [uv_angle]
  SIZE 10
 END
  TEXT " "
   LABEL
  SIZE 4
   ANGLE 45
 END
END
CLASS
 NAME "80 90"
 GROUP "SEA_CURARROW"
 EXPRESSION ([uv_length] >= 5 AND [uv_length] < 6)
 STYLE
  SYMBOL "arrow_wind"
  COLOR 255 51 0
   ANGLE [uv_angle]
  SIZE 10
 END
  TEXT " "
   LABEL
  SIZE 4
   ANGLE 45
 END
END
CLASS
 NAME "90 100"
 GROUP "SEA_CURARROW"
 EXPRESSION ([uv_length] >= 6 AND [uv_length] < 7)
 STYLE
  SYMBOL "arrow_wind"
  COLOR 222 0 0
   ANGLE [uv_angle]
  SIZE 10
 END
  TEXT " "
   LABEL
  SIZE 4
   ANGLE 45
 END
END
CLASS
 NAME "100 110"
 GROUP "SEA_CURARROW"
 EXPRESSION ([uv_length] >= 7 AND [uv_length] < 10)
 STYLE
  SYMBOL "arrow_wind"
  COLOR 128 0 0
   ANGLE [uv_angle]
  SIZE 10
 END
  TEXT " "
   LABEL
  SIZE 4
   ANGLE 45
 END
END
